### ISSUE TITLE
Update artboard doesn't function as expected

### ISSUE THREAD

**Issue by ChrisARaymond** [marvelapp/marvelapp_sketchplugin#17]
Instead of updating an artboard of the same name, it uploads the artboard so that it appears twice in the Marvel project screens. Then, when I attempt to delete the "newer" one, it deletes both versions, losing existing comments. This is a deal breaker for me.

**Comment by morz82** [comment]
Hey Chris,
This is an issue with the current version of Sketch, they are aware of it and have fixed it in the next release. It happens when a artboard is created using alt+drag, if you use copy and paste instead it will not have any issues
Sorry about this - I believe it's solved in the current Sketch beta if you want to give that a spin instead 

On Wed, Jul 13, 2016 at 9:50 PM +0100, "Chris Raymond" notifications@github.com wrote:

Instead of updating an artboard of the same name, it uploads the artboard so that it appears twice in the Marvel project screens. Then, when I attempt to delete the "newer" one, it deletes both versions, losing existing comments. This is a deal breaker for me.

**Comment by ChrisARaymond** [comment]
Hi Murat,

Your explanation isn’t really my use case. I had an artboard in Sketch, named Artboard1. It was drag and dropped into Marvel project at Time A. Now, I have updated that Artboard1 in Sketch, selected it, and went to the Sketch to Marvel plugin and selected Update Selected Artboard, and chose the Marvel project.

So, in Marvel, instead of replacing Artboard1, it added a second Artboard1. When I tried to delete the “new” version, both Artboard1s got deleted. I am guessing that unless you always used the plugin, you can’t start using it midway through a project. 

I just recall that I tried using the Sketch to Marvel plugin several weeks ago and got into the duplication issue then, it created a nightmare, so I stopped using it or the Dropbox sync, and simply started dragging and dropping images into Marvel projects. That was the only consistently safe way to not lose work. 

It seems like if the plugin only works if you start with a brand new Sketch file and a brand new Marvel project, that should be stated in the instructions. 

Does that make sense? In other words, you can’t start with method 1 (drag and drop) and then try to switch to method 2, Sketch to Marvel. I am sure no one imagined anyone would try to do that, I am clearly an edge case, but it would be great if that was explained from the get-go.

Thanks!

> On Jul 13, 2016, at 5:11 PM, Murat Mutlu notifications@github.com wrote:
> 
> Hey Chris,
> This is an issue with the current version of Sketch, they are aware of it and have fixed it in the next release. It happens when a artboard is created using alt+drag, if you use copy and paste instead it will not have any issues
> Sorry about this - I believe it's solved in the current Sketch beta if you want to give that a spin instead 
> 
> On Wed, Jul 13, 2016 at 9:50 PM +0100, "Chris Raymond" notifications@github.com wrote:
> 
> Instead of updating an artboard of the same name, it uploads the artboard so that it appears twice in the Marvel project screens. Then, when I attempt to delete the "newer" one, it deletes both versions, losing existing comments. This is a deal breaker for me.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub https://github.com/marvelapp/marvel-sketch/issues/17#issuecomment-232488135, or mute the thread https://github.com/notifications/unsubscribe/AG7irGu0qcLtM33i42pVT9t7ZHfWa825ks5qVVSNgaJpZM4JL1dT.

---

Chris Raymond
Senior UX Designer
SpeakAgent

**Comment by morz82** [comment]
Ah i see! In that case the delete issue is a bug for sure, we'll get that
sorted. The artboard in Sketch has a different unique ID to the one that is
dragged in so that makes two. It's not ideal, sorry about that

ᐧ

On 13 July 2016 at 22:30, Chris Raymond notifications@github.com wrote:

> Hi Murat,
> 
> Your explanation isn’t really my use case. I had an artboard in Sketch,
> named Artboard1. It was drag and dropped into Marvel project at Time A.
> Now, I have updated that Artboard1 in Sketch, selected it, and went to the
> Sketch to Marvel plugin and selected Update Selected Artboard, and chose
> the Marvel project.
> 
> So, in Marvel, instead of replacing Artboard1, it added a second
> Artboard1. When I tried to delete the “new” version, both Artboard1s got
> deleted. I am guessing that unless you always used the plugin, you can’t
> start using it midway through a project.
> 
> I just recall that I tried using the Sketch to Marvel plugin several weeks
> ago and got into the duplication issue then, it created a nightmare, so I
> stopped using it or the Dropbox sync, and simply started dragging and
> dropping images into Marvel projects. That was the only consistently safe
> way to not lose work.
> 
> It seems like if the plugin only works if you start with a brand new
> Sketch file and a brand new Marvel project, that should be stated in the
> instructions.
> 
> Does that make sense? In other words, you can’t start with method 1 (drag
> and drop) and then try to switch to method 2, Sketch to Marvel. I am sure
> no one imagined anyone would try to do that, I am clearly an edge case, but
> it would be great if that was explained from the get-go.
> 
> Thanks!
> 
> > On Jul 13, 2016, at 5:11 PM, Murat Mutlu notifications@github.com
> > wrote:
> > 
> > Hey Chris,
> > This is an issue with the current version of Sketch, they are aware of
> > it and have fixed it in the next release. It happens when a artboard is
> > created using alt+drag, if you use copy and paste instead it will not have
> > any issues
> > Sorry about this - I believe it's solved in the current Sketch beta if
> > you want to give that a spin instead
> > 
> > On Wed, Jul 13, 2016 at 9:50 PM +0100, "Chris Raymond" <
> > notifications@github.com> wrote:
> > 
> > Instead of updating an artboard of the same name, it uploads the
> > artboard so that it appears twice in the Marvel project screens. Then, when
> > I attempt to delete the "newer" one, it deletes both versions, losing
> > existing comments. This is a deal breaker for me.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/marvelapp/marvel-sketch/issues/17#issuecomment-232488135>,
> > or mute the thread <
> > https://github.com/notifications/unsubscribe/AG7irGu0qcLtM33i42pVT9t7ZHfWa825ks5qVVSNgaJpZM4JL1dT
> > .
> 
> ---
> 
> Chris Raymond
> Senior UX Designer
> SpeakAgent
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/marvelapp/marvel-sketch/issues/17#issuecomment-232492819,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADqm8PP5EMM3kbzB9jQ2cYuCp5Ocpib5ks5qVVj3gaJpZM4JL1dT
> .

## 

_Murat Mutlu_
Product Designer, Co-Founder
​
marvelapp.com | @marvelapp​ http://www.twitter.com/marvelapp

Twitter: @mutlu82 http://www.twitter.com/mutlu82
Skype: muratmutlu82
​LinkedIn: muratmutlu https://www.linkedin.com/in/muratmutlu

**Comment by abinashmohanty** [comment]
Ah! It seems I'm still facing the same issue using its latest sketch plugin @morz82
